# Generated by Django 4.0.2 on 2022-03-31 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='content',
        ),
        migrations.AddField(
            model_name='tweet',
            name='tweetAuthor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tweet',
            name='tweetText',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='tweetTitle',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
