# Generated by Django 4.0.2 on 2022-03-31 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0002_remove_tweet_content_tweet_tweetauthor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweetAuthor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweetText',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweetTitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
