# Generated by Django 4.0.2 on 2022-04-03 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_tweet_tweetdate_alter_tweet_tweettitletag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweetDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
